# Generated by Django 5.1.6 on 2025-04-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
