# Generated by Django 5.1.6 on 2025-04-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identities", "0003_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
