version: '3'

services:
  chatbot:
    build: ./chatbot
    container_name: flin-chatbot-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    env_file:
      - ./chatbot/.env
    volumes:
      - ./chatbot/knowledge:/app/knowledge
    networks:
      - flin-network

  # Nginx service
  nginx:
    image: nginx:1.23
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - chatbot
    networks:
      - flin-network

networks:
  flin-network:
    driver: bridge
